@baseUrl=http://localhost:3000

### GET all products
GET {{baseUrl}}/products

### GET product by id
GET {{baseUrl}}/products/1


### Create product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "description": "Description",
  "title": "title",
  "price": 1000,
  "category": "home",
  "image": "http://localhost:3000/http-cats/200"
}