@baseUrl=http://localhost:3000/users

### GET all users
GET {{baseUrl}}

### GET user by id
GET {{baseUrl}}/6

### CREATE new user
POST {{baseUrl}}
Content-Type: "application/json"

{
  "name": "Angelo Zambrano",
  "username": "angelozdev",
  "email": "angelo@ubidots.com",
  "asd": "asd"
}

### sada